# Конфигурация для добавления поля в классы Java
field:
  name: "BLACK_MINECRAFT" # Имя добавляемого поля
  value: "black-minecraft.com" # Значение добавляемого поля
  enabled: true # Включает или отключает добавление поля в классы

# Конфигурация для добавления комментариев в YAML файлы
comment: |
  #
  # Black-Minecraft
  #
commentEnabled: true # Включает или отключает добавление комментариев в YAML файлы

# Детализированный комментарий для добавления в ZIP-архив
detailedComment: |
  ################################# B M #################################
                    ___                  _
  #                | _ \  _     ____  __| | __                               #
  #                | __|_| |   / _  |/ _/ |/ /                               #
  #                |  _  \ |  / / | | / |   /  ____                          #
  #                | |_) | |__| |_| | \_|   \ /___/                          #
                   |_____|____\___,_|\__\_|\\_
  B          _                                                               B
  M  _     _(_)_   _  ___  ___ _ ___  ____ ____ _______   ___  ___  _     _  M
    | \   / | | \ | |/   \/ __|  ___|/ _  |  __|__   __| / _/ / _ \| \   / |
  # |  \_/  | |  \  |  $ | /  | |   / / | | |__   | |   / /  | | | |  \_/  | #
  # |       | | |\  |  __/ \__| |  |  |_| |  __|  | |  _\ \_ | |_| |       | #
  # |_|\_/|_|_|_| \_|___|___|_|   \___,_|_|     |_| (_)\\__\ \___/|_|\_/|_| #
  #                                                                          #
    ################################# B M #################################

                          BLACK-MINECRAFT.COM
detailedCommentEnabled: true # Включает или отключает добавление детализированного комментария в ZIP-архив

# Конфигурация для добавления поля в JSON файлы
bmField:
  name: "BM" # Имя добавляемого поля в JSON файлы
  value: "Black-Minecraft.com" # Значение добавляемого поля в JSON файлы
  enabled: true # Включает или отключает добавление поля в JSON файлы
