field:
  name: "BLACK_MINECRAFT"
  value: "black-minecraft.com"

comment: |
  #
  # Black-Minecraft
  #

detailedComment: |
  ################################# B M #################################
                    ___                  _
  #                | _ \  _     ____  __| | __                               #
  #                | __|_| |   / _  |/ _/ |/ /                               #
  #                |  _  \ |  / / | | / |   /  ____                          #
  #                | |_) | |__| |_| | \_|   \ /___/                          #
                   |_____|____\___,_|\__\_|\\_
  B          _                                                               B
  M  _     _(_)_   _  ___  ___ _ ___  ____ ____ _______   ___  ___  _     _  M
    | \   / | | \ | |/   \/ __|  ___|/ _  |  __|__   __| / _/ / _ \| \   / |
  # |  \_/  | |  \  |  $ | /  | |   / / | | |__   | |   / /  | | | |  \_/  | #
  # |       | | |\  |  __/ \__| |  |  |_| |  __|  | |  _\ \_ | |_| |       | #
  # |_|\_/|_|_|_| \_|___|___|_|   \___,_|_|     |_| (_)\\__\ \___/|_|\_/|_| #
  #                                                                          #
    ################################# B M #################################

                          BLACK-MINECRAFT.COM

bmField:
  name: "BM"
  value: "Black-Minecraft.comI"
